[theme]
primaryColor = "#FF4B4B"

[browser]
gatherUsageStats = false

[ui]
hideSidebarNav = false

[pages]
"Main" = "ğŸ  Main"
"Sentiment Analysis" = "ğŸ” Sentiment Analysis"
"Correlation Analysis" = "ğŸ”— Correlation Analysis"
"Trend Interpretation" = "ğŸ“Š Trend Interpretation"